### ISSUE TITLE
No attritute 'if_nametoindex' in socket since python3.8 on windows platform

### ISSUE THREAD

**Issue by flylzj** [MoshiBin/ssdpy#62]
**Describe the bug**
python3.7 on windows does not support the method 'if_nametoindex'

**Expected behavior**

```
  File "G:\language\python37\lib\site-packages\ssdpy\compat.py", line 31, in <module>
    if_nametoindex = socket.if_nametoindex
AttributeError: module 'socket' has no attribute 'if_nametoindex'
```

**Screenshots**
The document shows that the function was added on 3.8 on Windows

![{{)XYCFQ$5E{FRA BO3OAPR](https://user-images.githubusercontent.com/26559515/143149871-be4406ea-2819-454e-a6b4-e42d378449a7.png)
**Environment (please complete the following information):**
 - Python version: python3.7
 - SSDPy version: 0.4.1

**Comment by plusangel** [comment]
Confirmed that works with 3.8.10 in windows.
